from extensions import db
from models import School, Professor


def seed():
    schools = [
        School(code='SPIA', name='School of Public and International Affairs'),
        School(code='SITE', name='School of IT and Engineering'),
        School(code='SB',   name='School of Business'),
        School(code='LAW',  name='School of Law'),
        School(code='SAFS', name='School of Agricultural and Food Sciences'),
        School(code='SDA',  name='School of Design and Architecture'),
    ]
    db.session.add_all(schools)
    db.session.commit()

    spia = School.query.filter_by(code='SPIA').first()
    site = School.query.filter_by(code='SITE').first()
    sb = School.query.filter_by(code='SB').first()
    law = School.query.filter_by(code='LAW').first()
    safs = School.query.filter_by(code='SAFS').first()
    sda = School.query.filter_by(code='SDA').first()

    # SPIA
    spia_professors = [
        Professor(name='Azer Babayev',               title='Dean, Associate Professor',         specialization='Political Science',          image_url='https://www.ada.edu.az/media/2024/12/19/1to1_medium/azer_babayev_1_.jpg',         profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/1-azer-babayev',           school_id=spia.id),
        Professor(name='Orkhan Nadirov',             title='Associate Dean, Assistant Professor',specialization='Academic Affairs',           image_url='https://www.ada.edu.az/media/2025/01/21/1to1_medium/orkhan_nadirov_2_.jpg',        profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/9-orkhan-nadirov',          school_id=spia.id),
        Professor(name='Anar Valiyev',               title='Associate Professor',                specialization='Public Administration',       image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/anar_valiyev.jpg',             profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/2-anar-valiyev',            school_id=spia.id),
        Professor(name='Ferit Murat Ozkaleli',       title='Associate Professor',                specialization='International Affairs',       image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/ferit_murat_ozkaleli.jpg',     profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/3-ferit-murat-ozkaleli',    school_id=spia.id),
        Professor(name='Kavus Abushov',              title='Associate Professor',                specialization='Political Science',           image_url='https://www.ada.edu.az/media/2025/02/14/1to1_medium/_mg_4446.jpg',                 profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/4-kavus-abushov',           school_id=spia.id),
        Professor(name='Sarvar Gurbanov',            title='Associate Professor',                specialization='Economics',                  image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/sarvar_gurbanov.jpg',           profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/10-sarvar-gurbanov',         school_id=spia.id),
        Professor(name='Umut Ozkaleli',              title='Associate Professor',                specialization='Sociology',                  image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/umut_ozkaleli.jpg',             profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/5-umut-ozkaleli',           school_id=spia.id),
        Professor(name='Ali Saqer',                  title='Assistant Professor',                specialization='International Affairs',       image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/ali_saqer.jpg',                profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/7-ali-saqer',               school_id=spia.id),
        Professor(name='Amin Babazade',              title='Assistant Professor',                specialization='Economics',                  image_url='https://www.ada.edu.az/media/2024/09/12/1to1_medium/amin_babazada.jpg',             profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/364-amin-babazade',          school_id=spia.id),
        Professor(name='Daniel Pommier Vincelli',    title='Assistant Professor',                specialization='International Relations',     image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/daniel_pommier-1.jpg',         profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/6-daniel-pommier-vincelli', school_id=spia.id),
        Professor(name='Farkhad Aliyev',             title='Assistant Professor',                specialization='Political Science',           image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/farkhad_aliyev-1.jpg',         profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/363-farkhad-aliyev',         school_id=spia.id),
        Professor(name='Lala Jumayeva',              title='Assistant Professor',                specialization='International Affairs',       image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/lala_jumayeva.jpg',            profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/8-lala-jumayeva',            school_id=spia.id),
        Professor(name='Vener Garayev',              title='Assistant Professor',                specialization='Public Administration',       image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/vener_garayev-1.jpg',          profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/11-vener-garayev',           school_id=spia.id),
        Professor(name='Damjan Krnjevic Miskovic',   title='Professor of Practice',              specialization='Policy Research',            image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/damjan_krnjevic.jpg',           profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/12-damjan-krnjevic-miskovic',school_id=spia.id),
        Professor(name='Fariz Ismailzade',           title='Professor of Practice',              specialization='International Affairs',       image_url='https://www.ada.edu.az/media/2024/06/07/1to1_medium/fariz_i.jpeg',                 profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/393-fariz-ismailzade',        school_id=spia.id),
        Professor(name='Gulsabah Amirova',           title='Senior Instructor',                  specialization='Communication',              image_url='https://www.ada.edu.az/media/2024/09/12/1to1_medium/gulsabah_amirova.jpg',          profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/365-gulsabah-amirova',        school_id=spia.id),
        Professor(name='Nargiz Heydarova',           title='Instructor',                         specialization='Economics',                  image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/nargiz_heydarova.jpg',          profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/19-nargiz-heydarova',         school_id=spia.id),
        Professor(name='Vusal Mammadrzayev',         title='Senior Instructor',                  specialization='Decision Sciences',          image_url='https://www.ada.edu.az/media/2025/01/23/1to1_medium/vusal_mammadrzayev.jpg',        profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/15-vusal-mammadrzayev',       school_id=spia.id),
        Professor(name='Yuliya Aliyeva-Gureyeva',    title='Instructor',                         specialization='Social Sciences',            image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/yuliya_aliyeva.jpg',            profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/20-yuliya-aliyeva-gureyeva', school_id=spia.id),
        Professor(name='Neda Salahshour',            title='Assistant Professor',                specialization='Communication',              image_url='https://www.ada.edu.az/media/2025/12/15/1to1_medium/neda_salahshour.jpg',           profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/486-neda-salahshour',         school_id=spia.id),
        Professor(name='Bairam Akhundov',            title='Instructor',                         specialization='Public Administration',       image_url='https://www.ada.edu.az/media/2025/03/10/1to1_medium/bairam_akhundov.jpg',           profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/379-bairam-akhundov',         school_id=spia.id),
        Professor(name='Zhanat Alimanov',            title='Assistant Professor',                specialization='Law',                        image_url='https://www.ada.edu.az/media/2025/12/25/1to1_medium/zhanat_alimanov.jpg',           profile_url='https://www.ada.edu.az/en/schools/spia/members/faculty/490-zhanat-alimanov',         school_id=spia.id),
    ]
    db.session.add_all(spia_professors)
    db.session.commit()

    # SITE
    site_professors = [
        Professor(name='Abzatdin Adamov',    title='Dean, Professor',                                    specialization='Big Data Analytics',             image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/abzatdin_adamov.jpg',       profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/55-abzatdin-adamov',    school_id=site.id),
        Professor(name='Vugar Musayev',      title='Assistant Professor, Associate Dean',                specialization='Mathematics and Statistics',     image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/vugar_musayev.jpg',         profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/67-vugar-musayev',      school_id=site.id),
        Professor(name='Jamaladdin Hasanov', title='Associate Professor, Director of BSIT Program',     specialization='Computer and Information Sciences',image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/jamaladdin_hasanov.jpg',    profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/63-jamaladdin-hasanov', school_id=site.id),
        Professor(name='Samir Rustamov',     title='Associate Professor, Director of BSCS Program',     specialization='Computer and Information Sciences',image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/samir_rustamov.jpg',        profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/57-samir-rustamov',     school_id=site.id),
        Professor(name='Wisam Al-Dayyeni',   title='Assistant Professor, Program Director CE & EEE',    specialization='Electrical Engineering',         image_url='https://www.ada.edu.az/media/2024/10/09/1to1_medium/ada_picture_v2.jpg',        profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/70-wisam-al-dayyeni',   school_id=site.id),
        Professor(name='Yagub Aliyev',       title='Associate Professor, Program Director Mathematics', specialization='Mathematics and Statistics',     image_url='https://www.ada.edu.az/media/2025/01/13/1to1_medium/yagub_aliyev.jpg',          profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/68-yagub-aliyev',       school_id=site.id),
        Professor(name='Araz Yusubov',       title='Assistant Professor',                               specialization='Computer and Information Sciences',image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/araz_yusubov.jpg',          profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/58-araz-yusubov',       school_id=site.id),
        Professor(name='Burcu Ramazanli',    title='Assistant Professor',                               specialization='Engineering',                    image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/burcu_ramazanli.jpg',        profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/59-burcu-ramazanli',    school_id=site.id),
        Professor(name='Elchin Hasanalizade',title='Assistant Professor',                               specialization='Mathematics',                    image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/elchin_hasanalizada.jpg',    profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/60-elchin-hasanalizade',school_id=site.id),
        Professor(name='Fuad Hajiyev',       title='Assistant Professor',                               specialization='Mathematics',                    image_url='https://www.ada.edu.az/media/2025/01/10/1to1_medium/fuad_hajiyev.jpg',           profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/61-fuad-hajiyev',       school_id=site.id),
        Professor(name='Gulmammad Mammadov', title='Assistant Professor',                               specialization='Physics',                        image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/gulmammad_mammadov.jpg',     profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/62-gulmammad-mammadov', school_id=site.id),
        Professor(name='Javanshir Azizov',   title='Assistant Professor',                               specialization='Mathematics',                    image_url='https://www.ada.edu.az/media/2025/01/10/1to1_medium/javanshir_azizov.jpg',       profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/73-javanshir-azizov',   school_id=site.id),
        Professor(name='John Thomas Burns',  title='Assistant Professor',                               specialization='Computer and Information Sciences',image_url='https://www.ada.edu.az/media/2025/01/14/1to1_medium/john_thomas_burns.jpg',     profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/375-john-thomas-burns', school_id=site.id),
        Professor(name='Mykhailo Medvediev', title='Assistant Professor',                               specialization='Computer and Information Sciences',image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/mykhailo_medvediev.jpg',    profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/64-mykhailo-medvediev', school_id=site.id),
        Professor(name='Orkhan Karimzada',   title='Assistant Professor',                               specialization='Electrical Engineering',         image_url='https://www.ada.edu.az/media/2025/01/10/1to1_medium/orkhan_karimzada.jpg',       profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/66-orkhan-karimzada',   school_id=site.id),
        Professor(name='Rashad Aliyev',      title='Assistant Professor',                               specialization='Computer and Information Science',image_url='https://www.ada.edu.az/media/2025/02/21/1to1_medium/photo_2025_02_20_15_10_00.jpg',profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/372-rashad-aliyev',    school_id=site.id),
        Professor(name='Samin Malik',        title='Assistant Professor',                               specialization='Mathematics',                    image_url='https://www.ada.edu.az/media/2025/01/10/1to1_medium/samin_malik.jpg',            profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/65-samin-malik',        school_id=site.id),
        Professor(name='Rafail Alizade',     title='Associate Professor',                               specialization='Mathematics',                    image_url='https://www.ada.edu.az/media/2025/01/10/1to1_medium/rafail_alizada.jpg',         profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/56-rafail-alizade',     school_id=site.id),
        Professor(name='Ismayil Shahaliyev', title='Instructor',                                        specialization='Information and Computer Sciences',image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/ismayil_shahaliyev.jpg',    profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/72-ismayil-shahaliyev', school_id=site.id),
        Professor(name='Nuraddin Sadili',    title='Senior Instructor',                                 specialization='Computer and Information Sciences',image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/nuraddin_sadili.jpg',       profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/76-nuraddin-sadili',    school_id=site.id),
        Professor(name='Orkhan Mammadov',    title='Instructor',                                        specialization='Computer and Information Sciences',image_url='https://www.ada.edu.az/media/2025/01/15/1to1_medium/orkhan_mammadov-1.jpg',     profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/373-orkhan-mammadov',   school_id=site.id),
        Professor(name='Pasha Pashazade',    title='Instructor',                                        specialization='Computer Engineering',            image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/pasha_pashazade.jpg',        profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/77-pasha-pashazade',    school_id=site.id),
        Professor(name='Samir Mammadov',     title='Instructor',                                        specialization='Computer and Information Sciences',image_url='https://www.ada.edu.az/assets/img/content/schools-it/member24.jpeg',           profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/78-samir-mammadov',     school_id=site.id),
        Professor(name='Ruslan Muslumov',    title='Assistant Professor',                               specialization='Mathematics',                    image_url='https://www.ada.edu.az/media/2025/10/09/1to1_medium/ruslan_muslumov.jpg',        profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/469-ruslan-muslumov',   school_id=site.id),
        Professor(name='Said Pashayev',      title='Assistant Professor',                               specialization='Physics',                        image_url='https://www.ada.edu.az/media/2025/12/11/1to1_medium/said_pashayev.jpg',          profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/480-said-pashayev',     school_id=site.id),
        Professor(name='Natig Atakishiyev',  title='Professor',                                         specialization='Mathematics',                    image_url='https://www.ada.edu.az/media/2025/12/11/1to1_medium/natig_atakishiyev.jpg',      profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/481-natig-atakishiyev', school_id=site.id),
        Professor(name='Alexz Farrall',      title='Assistant Professor',                               specialization='Computer Engineering',            image_url='https://www.ada.edu.az/media/2025/12/12/1to1_medium/alexz_farraii.jpg',         profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/483-alexz-farrall',     school_id=site.id),
        Professor(name='Azar Aliyev',        title='Instructor',                                        specialization='Computer and Information Sciences',image_url='https://www.ada.edu.az/media/2025/12/12/1to1_medium/azar_aliyev.jpg',           profile_url='https://www.ada.edu.az/en/schools/site/members/faculty/484-azar-aliyev',       school_id=site.id),
    ]
    db.session.add_all(site_professors)
    db.session.commit()

    # SB
    sb_professors = [
        Professor(name='Huseyn Ismayilov',   title='Dean, School of Business',           specialization='School of Business',           image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/huseyn_ismayilov.jpg',     profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Ruslan Aliyev',      title='Associate Dean, Academic Affairs',   specialization='Economics',                    image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/ruslan_aliyev.jpg',        profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Elkin Nurmammadov',  title='Vice Rector, Academic Affairs',      specialization='Economics',                    image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/elkin_nurmammadov.jpg',    profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Ali Gunesh',         title='Associate Professor',                specialization='Economics',                    image_url='https://www.ada.edu.az/media/2025/04/02/1to1_medium/ali_gunesh.jpg',           profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Aysel Bandad',       title='Senior Instructor',                  specialization='Economics',                    image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/aysel_bandad.jpg',         profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Azar Abizada',       title='Professor',                          specialization='Economics',                    image_url='https://www.ada.edu.az/media/2025/04/02/1to1_medium/azar_abizada.jpg',         profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Azra Brankovic',     title='Visiting Professor',                 specialization='International Business',        image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/azra_brankovic.jpg',       profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Elnur Eyvazov',      title='Lead Instructor',                    specialization='Legal Professions and Studies',image_url='https://www.ada.edu.az/assets/img/content/schools-business/member17.jpg',     profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Emin Ilyas',         title='Senior Instructor',                  specialization='Operations Management',        image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/emin_ilyas.jpg',           profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Farid Gadirli',      title='Assistant Professor',                specialization='Finance',                      image_url='https://www.ada.edu.az/media/2025/09/22/farid_farzali_gadirli-1.jpg',          profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Farkhad Huseynov',   title='Professor',                          specialization='Mathematics and Economics',    image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/farkhad_huseynov-1.jpg',   profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Fuzuli Aliyev',      title='Assistant Professor',                specialization='Finance',                      image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/fuzuli_aliyev.jpg',         profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Hayfaa Tlaiss',      title='Professor',                          specialization='Management',                   image_url='https://www.ada.edu.az/media/2024/11/30/1to1_medium/hayfaa_tlaiss-1.jpg',      profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Hulisi Ogut',        title='Visiting Professor',                 specialization='Information Systems',          image_url='https://www.ada.edu.az/media/2025/04/02/1to1_medium/hulisi_ogut.jpg',          profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Ismayil Jafarov',    title='Senior Instructor',                  specialization='Mathematics and Statistics',   image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/ismayil_jafarov.jpg',      profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Kerim Keskin',       title='Associate Professor',                specialization='Economics',                    image_url='https://www.ada.edu.az/media/2024/12/18/1to1_medium/kerim_keskin.jpg',         profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Mehriban Ahmadova',  title='Instructor',                         specialization='Accounting',                   image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/mehriban_ahmadova.jpg',    profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Mugabil Isayev',     title='Assistant Professor',                specialization='Finance',                      image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/mugabil_isayev.jpg',        profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Muharrem Yesilirmak',title='Associate Professor',                specialization='Economics',                    image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/muharrem_yeshilirmak.jpg', profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Narmina Rustamova',  title='Instructor',                         specialization='Economics',                    image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/narmina_rustamova.jpg',     profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Omar Farooq',        title='Professor',                          specialization='Finance and Financial Management',image_url='https://www.ada.edu.az/assets/img/content/schools-business/member3.jpg',   profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Samir Orujov',       title='Assistant Professor',                specialization='Mathematics and Statistics',   image_url='https://www.ada.edu.az/media/2025/04/02/1to1_medium/samir_orujov.jpg',         profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
        Professor(name='Zaur Abdullazade',   title='Instructor',                         specialization='Accounting',                   image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/zaur_abdullazada.jpg',     profile_url='https://www.ada.edu.az/en/schools/sb', school_id=sb.id),
    ]
    db.session.add_all(sb_professors)
    db.session.commit()

    # LAW
    law_professors = [
        Professor(name='Rashad Ibadov',                title='Dean',                                specialization='School of Law',   image_url='https://www.ada.edu.az/media/2024/06/07/1to1_medium/rashad_i.jpeg',            profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Javid Gadirov',                title='Associate Dean, Assistant Professor', specialization='Law',             image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/javid_gadirov.jpg',        profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Azad Talibov',                 title='Associate Professor',                 specialization='Law',             image_url='https://www.ada.edu.az/media/2024/06/05/1to1_medium/azad_talibov.jpg',         profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Farid Ahmadov',                title='Associate Professor',                 specialization='Law',             image_url='https://www.ada.edu.az/assets/img/content/schools-law/member3.jpeg',          profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Anar Jafarov',                 title='Assistant Professor',                 specialization='Philosophy',      image_url='https://www.ada.edu.az/media/2024/09/09/1to1_medium/anar_jafarov.jpg',         profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Aynur Akhundli',               title='Assistant Professor',                 specialization='Law',             image_url='https://www.ada.edu.az/media/2024/06/05/1to1_medium/aynur_akhundlu.jpg',       profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Kamala Nazarova',              title='Assistant Professor',                 specialization='Law',             image_url='https://www.ada.edu.az/media/2024/06/05/1to1_medium/kamala_nazarova.jpg',      profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Altay Mustafayev',             title='Professor of Practice',               specialization='Law',             image_url='https://www.ada.edu.az/assets/img/content/schools-law/member7.jpeg',          profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Juan Rodrigo Labardini Flores',title='Professor of Practice',               specialization='Law',             image_url='https://www.ada.edu.az/media/2024/05/31/1to1_medium/rodrigo_labardini.jpg',    profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Emin Karimov',                 title='Professor of Practice',               specialization='Law',             image_url='https://www.ada.edu.az/media/2024/12/27/1to1_medium/emin_karimov.jpg',         profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Abiddin Huseynov',             title='Adjunct Professor of Legal Practice', specialization='Law',             image_url='https://www.ada.edu.az/assets/img/content/schools-law/member8.jpeg',          profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Justice Khagani Mammadov',     title='Adjunct Professor of Legal Practice', specialization='Law',             image_url='https://www.ada.edu.az/assets/img/content/schools-law/member10.jpg',          profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Mahir Abbasov',                title='Adjunct Lecturer',                    specialization='Law',             image_url='https://www.ada.edu.az/assets/img/content/schools-law/member11.jpeg',         profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Zaur Naghiyev',                title='Adjunct Lecturer',                    specialization='Law',             image_url='https://www.ada.edu.az/assets/img/content/schools-law/member12.jpeg',         profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Elnur Karimov',                title='Assistant Professor',                 specialization='Law',             image_url='https://www.ada.edu.az/media/2025/11/27/1to1_medium/elnur_karimov.jpg',        profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Tabriz Jafarov',               title='Assistant Professor',                 specialization='Law',             image_url='https://www.ada.edu.az/media/2025/12/25/1to1_medium/tabriz_jafarov.jpg',       profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Dunyamin Novruzov',            title='Assistant Professor',                 specialization='Law',             image_url='https://www.ada.edu.az/media/2026/02/13/1to1_medium/dunyamin_novruzov.jpg',    profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
        Professor(name='Shahlar Mammadov',             title='Professor',                           specialization='Practice in Law', image_url='https://www.ada.edu.az/media/2026/04/03/1to1_medium/shahlar_mammadov.jpg',     profile_url='https://www.ada.edu.az/en/schools/law', school_id=law.id),
    ]
    db.session.add_all(law_professors)
    db.session.commit()

    # SAFS
    safs_professors = [
        Professor(name='Matteo Vittuari',  title='Dean',                specialization='Agricultural and Food Policy', image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/matteo_vittuari-1.jpg',        profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
        Professor(name='Saida Aliyeva',    title='Assistant Professor', specialization='Food Sciences',               image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/saida_aliyeva.jpg',            profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
        Professor(name='Asaf Omarov',      title='Assistant Professor', specialization='Animal Sciences',             image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/asaf_omarov.jpg',              profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
        Professor(name='Madina Guliyeva',  title='Assistant Professor', specialization='Food Sciences',               image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/madina_guliyeva.jpg',          profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
        Professor(name='Sahil Guliyev',    title='Assistant Professor', specialization='Agricultural Sciences',       image_url='https://www.ada.edu.az/media/2026/01/29/1to1_medium/sahil_guliyev_safs.jpg',       profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
        Professor(name='Mehraj Abbasov',   title='Assistant Professor', specialization='Agricultural Sciences',       image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/mehraj_abbasov_copy.jpg',      profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
        Professor(name='Matilde Tura',     title='Visiting Professor',  specialization='Food Sciences',               image_url='https://www.ada.edu.az/media/2025/09/29/1to1_medium/matilde_tura_jpg.webp',        profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
        Professor(name='Marcello Russo',   title='Visiting Professor',  specialization='Agricultural Sciences',       image_url='https://www.ada.edu.az/media/2025/09/29/1to1_medium/1690519201948.jpeg',           profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
        Professor(name='Giacomo Zanello',  title='Visiting Professor',  specialization='Agricultural Sciences',       image_url='https://www.ada.edu.az/media/2025/09/29/1to1_medium/whatsapp_image_2025_09_29_at_15_40_00.jpeg', profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
        Professor(name='Cesare Zanasi',    title='Visiting Professor',  specialization='Agricultural Sciences',       image_url='https://www.ada.edu.az/media/2025/09/29/1to1_medium/foto.png',                     profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
        Professor(name='William H. Meyers',title='Visiting Professor',  specialization='Agricultural Economics',      image_url='https://www.ada.edu.az/media/2025/09/29/1to1_medium/williammeyers.jpg',            profile_url='https://www.ada.edu.az/en/schools/safs', school_id=safs.id),
    ]
    db.session.add_all(safs_professors)
    db.session.commit()

    # SDA
    sda_professors = [
        Professor(name='Silvia Ferraris',         title='Dean, School of Design & Architecture', specialization='Design',                       image_url='https://www.ada.edu.az/media/2025/07/28/img_0506-1.jpeg',                            profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Marco Bovati',            title='Associate Dean',                        specialization='Architectural and Urban Design',image_url='https://www.ada.edu.az/media/2024/12/03/1to1_medium/photo_2024_12_03_15_45_04-1.jpg',profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Nora Lombardini',         title='Associate Dean',                        specialization='Architectural Conservation',    image_url='https://www.ada.edu.az/media/2024/09/30/1to1_medium/photo_2024_09_30_12_31_09.jpg',  profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Emir Huseynov',           title='Assistant Professor',                   specialization='Architecture',                  image_url='https://www.ada.edu.az/media/2024/06/05/1to1_medium/emir_huseynov.jpg',              profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Leyla Hasanova',          title='Assistant Professor',                   specialization='Architectural Design',          image_url='https://www.ada.edu.az/media/2024/06/05/1to1_medium/leyla_hasanova.jpg',             profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Carl Haddrell',           title='Assistant Professor',                   specialization='Design',                       image_url='https://www.ada.edu.az/media/2025/07/25/1to1_medium/carl_haddrell_photo.jpg',         profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Stefania Sini',           title='Visiting Assistant Professor',          specialization='Architecture and Design',       image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/stefania_sini.jpg',              profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Melania Vicentini',       title='Visiting Assistant Professor',          specialization='Design',                       image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/melania_vicentini.jpg',          profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Ermes Invernizzi',        title='Visiting Assistant Professor',          specialization='Architecture',                  image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/ermes_invernizzi.jpg',           profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Dina Jovanovic Lombardo', title='Visiting Assistant Professor',          specialization='Architecture and Design',       image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/dina_jovanovic.jpg',             profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Angel Cordero Ampuero',   title='Visiting Associate Professor',          specialization='Architecture',                  image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/angel_ampuero.jpg',              profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Deniz Ozge Aytac',        title='Assistant Professor',                   specialization='Interior Design',               image_url='https://www.ada.edu.az/media/2025/11/20/1to1_medium/deniz_ozge_aytac.jpg',           profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Nigar Aghayeva',          title='Adjunct Instructor of Mathematics',     specialization='Architecture',                  image_url='https://www.ada.edu.az/media/2025/10/15/1to1_medium/screenshot_2025_10_15_at_16_44_36.png',profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
        Professor(name='Lala Guluzada',           title='Assistant Professor',                   specialization='Design',                       image_url='https://www.ada.edu.az/media/2026/02/09/1to1_medium/lala_guluzada.jpg',              profile_url='https://www.ada.edu.az/en/schools/sda', school_id=sda.id),
    ]
    db.session.add_all(sda_professors)
    db.session.commit()

    print(f"Seeded: {School.query.count()} schools, {Professor.query.count()} professors")